services:
  api-gateway:
    build:
      context: ../services/api-gateway
      dockerfile: Dockerfile
    container_name: kalendas-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - ./config/env/gateway.env
    networks:
      - kalendas-net
    depends_on:
      - calendar-service
      - event-service
      - comment-service
      - notification-service

  calendar-service:
    build:
      context: ../services/calendar-service
      dockerfile: Dockerfile
    container_name: kalendas-calendar
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - ./config/env/calendar.env
    networks:
      - kalendas-net

  event-service:
    build:
      context: ../services/event-service
      dockerfile: Dockerfile
    container_name: kalendas-event
    restart: unless-stopped
    ports:
      - "3002:3002"
    env_file:
      - ./config/env/event.env
    networks:
      - kalendas-net

  comment-service:
    build:
      context: ../services/comment-service
      dockerfile: Dockerfile
    container_name: kalendas-comment
    restart: unless-stopped
    ports:
      - "3003:3003"
    env_file:
      - ./config/env/comment.env
    networks:
      - kalendas-net

  notification-service:
    build:
      context: ../services/notification-service
      dockerfile: Dockerfile
    container_name: kalendas-notification
    restart: unless-stopped
    ports:
      - "3004:3004"
    env_file:
      - ./config/env/notification.env
    networks:
      - kalendas-net

  webapp:
    build:
      context: ../webapp
      dockerfile: Dockerfile
    container_name: kalendas-webapp
    restart: unless-stopped
    ports:
      - "5173:5173"
    env_file:
      - ./config/env/webapp.env
    networks:
      - kalendas-net
    depends_on:
      - api-gateway

networks:
  kalendas-net:
    driver: bridge
